### ISSUE TITLE
Improve serialization and various

### ISSUE THREAD

**Issue by bowring** [JsonHrdwick/BeverageProject#5]
- [x] simplify serializeToCSV : Files.writeString(path, filestring);
 - [x] create Beverage method: public String prettyPrintCSV()
 - [x] error checking in deserializeFromCSV: size of data?; provide default values; trim() each attribute
 - [x] Method 'main()' does not have signature 'public **static** void main(String[])' 
 - [x] run Code/Reformat File to clean up
 - [x] test equals override by using breakpoint in Driver.main and changing the output CSV file after it is written, but before reading

**Comment by JsonHrdwick** [comment]
Could you elaborate on the functionality of prettyPrintCSV(). I assume you want this method to process the delimiting concatenation of the _filestring_ variable.

**Comment by bowring** [comment]
yep - separation of concerns (look it up); also research "SOLID" design principles
