### ISSUE TITLE
serialization of collections

### ISSUE THREAD

**Issue by bowring** [JsonHrdwick/BeverageProject#6]
- [x] build on what you have to handle collections of Beverage objects instead of singletons
- [x] Hint: Set interface

**Comment by bowring** [comment]
I don’t see collections code.

**Comment by bowring** [comment]
Sorry, I was on a phone.  I sse what you are trying to do, but much needs talking about ... how about a meeting next Monday 10 AM?
 ps I can't reopen issue

**Comment by JsonHrdwick** [comment]
Yes that works for me. I was going to research #7 this weekend as well.
